### ISSUE TITLE
Is this repository unmaintained?

### ISSUE THREAD

**Issue by yn5** [vimeo/openapi#17]
It seems the specification is not in sync with the actual response(s?) of the API, at least for the `https://api.vimeo.com/me/videos` response.

I see the response is returning a `player_embed_url` field that I can't seem to find in the spec.

A simple search for `player_embed_url` in https://raw.githubusercontent.com/vimeo/openapi/master/api.yaml shows no results and is the basis for my question.

**Comment by erunion** [comment]
Unfortunately yes. I was the only one who was updating this in a regular basis and after I left the company in 2019 nobody else picked up the OpenAPI torch internally.

Sorry. 😔

**Comment by yn5** [comment]
@erunion No need to be sorry! Thanks a lot for your quick response and the work you did!
